escamboapp/config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'

end

escamboapp/app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :category
  belongs_to :member
end

escamboapp/app/models/admin.rb
class Admin < ActiveRecord::Base

  ROLES = {:full_access => 0, :restricted_access => 1}

  enum role: ROLES

  scope :with_full_access, -> {where(role: ROLES[:full_access])}
  scope :with_restricted_access, -> {where(role: ROLES[:restricted_access])}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def role_br
    if self.role == 'full_access'
      'Acesso Completo'
    else
      'Acesso Restrito'
    end
  end
end

escamboapp/app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :description
end

escamboapp/app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Pundit
  include Pundit

  #Manages Pundit Errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  #Set Layout
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_device"
    else
      "application"
    end
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

escamboapp/app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only:[:edit, :update, :destroy]

  def index
    #@admins = Admin.all
    #@admins = Admin.with_full_acess
    @admins = policy_scope(Admin)

  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "The admin (#{@admin.email}) its succeful cadastred"
    else
      render :new
    end
  end

  def edit
  end

  def update
    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if  @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "The admin (#{@admin.email}) its succeful update"
    else
      render :edit
    end
  end

  def destroy
    admin_email = @admin.email
    if  @admin.destroy
      redirect_to backoffice_admins_path, notice: "The admin (#{admin_email}) its succeful deleted"
    else
      render :index
    end
  end

  private

  def params_admin
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end
end

escamboapp/app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only:[:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "The category(#{@category.description}) its succeful cadastred"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if  @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "The category(#{@category.description}) its succeful update"
    else
      render :edit
    end
  end

  private

  def params_category
    params.require(:category).permit(:description)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

escamboapp/app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end
end

escamboapp/app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
end

escamboapp/app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_message(current_admin, params[:'recipient-name'], params[:'subject-text'], params[:'message-text']).deliver_now
      @notify_message = "Email enviado com sucesso!"
      @notify_flag = "success"
    rescue
      @notify_message = "Erro ao enviar o email, tente novamente"
      @notify_flag = "error"
    end
    respond_to do |format|
      format.js
    end
  end
end

escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
    current_admin 
  end

end

escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"

  def index
    @categories = Category.all
  end
end

escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
end

escamboapp/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

end

escamboapp/app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

escamboapp/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

escamboapp/app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

escamboapp/app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form",
           locals: {action: "Edit Admin"}
%>

escamboapp/app/views/backoffice/admins/index.html.erb
<h1 class="page-header"> Admins </h1>

<div class="panel panel-default">
<div class="panel-heading">
    Administradores

    <%if policy(@admins).new?%>
      <%= link_to  new_backoffice_admin_path, class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do%>
        <i class="fa fa-plus "></i>
      <%end%>
    <%end%>
</div>
  <div class="panel-body">
      <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>Nome</th>
                      <th>Email</th>
                      <th>Tipo de Acesso </th>
                  </tr>
              </thead>
              <tbody>
                  <% @admins.each do |admin| %>
                      <tr>
                          <td><%= admin.id %></td>
                          <td><%= admin.name %></td>
                          <td><%= admin.email %></td>
                          <td><%= admin.role_br %></td>
                          <td style='width: 150px'>
                            <%= link_to edit_backoffice_send_mail_path(admin), class:"btn btn-info btn-circle",
                            remote: true do%>
                              <i class="fa fa-envelope"></i>
                            <%end%>
                            <%= link_to edit_backoffice_admin_path(admin), class:"btn btn-primary btn-circle" do%>
                              <i class="fa fa-edit"></i>
                            <%end%>
                            <% if current_admin.id != admin.id %>
                              <%= link_to backoffice_admin_path(admin), method: :delete,
                              class:"btn btn-danger btn-circle", data:{confirm: "Você deseja excluir #{admin.email}?"} do%>
                                <i class="fa fa-times"></i>
                              <%end%>
                            <%end%>
                          </td>
                      </tr>
                  <%end%>
              </tbody>
          </table>
      </div>
  </div>
</div>

<%= render partial: 'backoffice/admins/shared/send_mail'%>

escamboapp/app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form",
           locals: {action: "Adicionando Admin"}
%>

escamboapp/app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
<% if @admin.errors.any?%>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
        <% @admin.errors.full_messages.each do |message|%>
          <li><%= message %></li>
        <%end%>
    </ul>

    </div>
<%end%>

<div class="panel panel-default">
  <div class="panel-heading">
      <%= action %>
  </div>
    <div class="panel-body">
      <div class="col-lg-6">
        <%= form_for([:backoffice,@admin]) do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class:"form-control",placeholder:"Nome do Adminstrador"%>
        </div>
          <div class="form-group">
            <label>Email</label>
            <%= f.text_field :email, class:"form-control",placeholder:"Emails do Adminstrador"%>
          </div>
          <div class="form-group">
            <label>Senha</label>
            <%= f.password_field :password, class:"form-control",placeholder:"Senha"%>
          </div>
          <div class="form-group">
            <label>Confirmação da Senha</label>
            <%= f.password_field :password_confirmation, class:"form-control",placeholder:"Confirmação da Senha"%>
          </div>
          <button type="submit" class="btn btn-default">Save</button>
        <% end %>
      </div>
    </div>
</div>

escamboapp/app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path , remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <%=text_field_tag(:'recipient-name', nil, class: "form-control",readonly: "readonly")%>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Subject:</label>
            <%=text_field_tag(:'subject-text', nil, class: "form-control")%>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <%=text_area_tag(:'message-text', nil, class: "form-control")%>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= submit_tag 'Send Message', class:"btn btn-primary"%>
      </div>
      <%end%>
    </div>
  </div>
</div>

escamboapp/app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form",
           locals: {action: "Edit Category"}
%>

escamboapp/app/views/backoffice/categories/index.html.erb
<h1 class="page-header"> Categories </h1>
<div class="panel panel-default">
<div class="panel-heading">
    Listando Categorias
    <%= link_to new_backoffice_category_path, class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do%>
      <i class="fa fa-plus "></i>
    <%end%>
</div>
  <div class="panel-body">
      <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>Description</th>
                  </tr>
              </thead>
              <tbody>
                  <% @categories.each do |category| %>
                      <tr>
                          <td><%= category.id %></td>
                          <td><%= category.description %></td>
                          <td style='width: 150px'>
                            <%= link_to edit_backoffice_category_path(category), class:"btn btn-primary btn-circle" do%>
                              <i class="fa fa-edit"></i>
                            <%end%>
                            <button type="button" disabled="disabled" class="btn btn-danger btn-circle">
                              <i class="fa fa-times"></i>
                            </button>
                          </td>
                      </tr>
                  <%end%>
              </tbody>
          </table>
      </div>
  </div>
</div>

escamboapp/app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form",
           locals: {action: "New Category"}
%>

escamboapp/app/views/backoffice/categories/shared/_form.html.erb
<h1 class="page-header">Categories</h1>
<% if @category.errors.any?%>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
        <% @category.errors.full_messages.each do |message|%>
          <li><%= message %></li>
        <%end%>
    </ul>

    </div>
<%end%>

<div class="panel panel-default">
  <div class="panel-heading">
      <%= action %>
  </div>
    <div class="panel-body">
      <div class="col-lg-6">
        <%= form_for([:backoffice,@category]) do |f| %>
          <div class="form-group">
            <label>Description</label>
            <%= f.text_field :description, class:"form-control",placeholder:"Ex: Animais"%>
          </div>
          <button type="submit" class="btn btn-default">Save</button>
        <% end %>
      </div>
    </div>
</div>

escamboapp/app/views/backoffice/dashboard/index.html.erb
<h1 class="page-header">DashBoard</h1>

escamboapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escamboapp</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

escamboapp/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Escamboapp</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'backoffice', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag 'backoffice'%>
    <%= csrf_meta_tags %>
</head>

<body>
    <div id="wrapper">
      <%= render partial: "layouts/backoffice_shared/navigation" %>
      <div id="page-wrapper">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-12">
                    <%= yield %>
                  </div>
              </div>
          </div>
      </div>
    </div>
    <%if notice%>
      <%= javascript_tag "$.notify('#{notice}', 'success')"; %>
    <%end%>
    <%if alert%>
      <script>
        $.notify("<%= alert %>", "error");
      </script>
    <%end%>



</body>

</html>

escamboapp/app/views/layouts/backoffice_device.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Escamboapp</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= stylesheet_link_tag    'backoffice', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag 'backoffice'%>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <%= yield %>
</body>

</html>

escamboapp/app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">BackOffice - Escamboapp</a>
    </div>

    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">
        <li><%= current_admin.email%></li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                    <i class="fa fa-sign-out fa-fw"></i>
                    Logout
                  <%end%>
                </li>
            </ul>
        </li>
    </ul>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <%= link_to backoffice_path do %>
                      <i class="fa fa-dashboard fa-fw"></i> Dashboard
                    <%end%>
                </li>
                <li>
                    <%= link_to backoffice_categories_path do %>
                      <i class="fa fa-th-list fa-fw"></i> Categories
                    <%end%>
                </li>
                <li>
                    <%= link_to backoffice_admins_path do %>
                      <i class="fa fa-users fa-fw"></i> Administrations
                    <%end%>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

escamboapp/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Escamboapp</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'site', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag 'site'%>
    <%= csrf_meta_tags %>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

  </head>

  <body>
    <%= render partial: "layouts/site_shared/navigation" %>
    <%= yield %>
    <%= render partial: "layouts/site_shared/footer" %>
  </body>

</html>

escamboapp/app/views/layouts/site_shared/_footer.html.erb
<div class="container">
    <hr>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>
</div>

escamboapp/app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Start Bootstrap</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li>
                      <a href="#">About</a>
                  </li>
                  <li>
                      <a href="#">Services</a>
                  </li>
                  <li>
                      <a href="#">Contact</a>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>